print('====== DESAFIO 009 ======')
#Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada.
print('='*40)
nm = int(input('Escolha um número para ver sua taboada: '))
print('{} x 01 = {}'.format(nm, nm*1))
print('{} x 02 = {}'.format(nm, nm*2))
print('{} x 03 = {}'.format(nm, nm*3))
print('{} x 04 = {}'.format(nm, nm*4))
print('{} x 05 = {}'.format(nm, nm*5))
print('{} x 06 = {}'.format(nm, nm*6))
print('{} x 07 = {}'.format(nm, nm*7))
print('{} x 08 = {}'.format(nm, nm*8))
print('{} x 09 = {}'.format(nm, nm*9))
print('{} x 10 = {}'.format(nm, nm*10))
print('='*40)
